config/routes.rb
Rails.application.routes.draw do
  # root route
    # controller#action 
  root 'subs#index'

  # resources
    # resources :controller
    resources :subs do
      resources :topics
    end

    resources :topics do
      resources :comments
    end
    
    # only: [:index, :show]
    # can also do except: [:routes]
    # generates all necessary routes/prefixes
    # http://localhost:3000/rails/info/routes

  # custom routes
    # http verb 'controller/action', as: bananas
    # get '/edit', to: 'subs#edit'
    # get '/show', to: 'subs#show'
    # get '/subs/:id' to: 'subs#destroy'


    # /subs/1/topics/1
    # /subs/:sub_id/topics/:id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
end

app/models/sub.rb
class Sub < ApplicationRecord
  has_many :topics
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_topic


  def new
    @comment = @topic.comments.new
  end

  def create
    @comment = @topic.comments.new(comment_params)
    if @comment.saves
      # do something
    else
      render :new
    end
  end

  private
  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
# Model - all logic on the table or record, restraints, associations
# Views - user interaction, logic at minimum
# Controller - directs traffic, actions

  # CRUD      HTTP VERBS
  # Create  -> POST
  # Read    -> GET
  # Update  -> PATCH / PUT
  # Destroy -> DELETE

  # All actions must return a response
    # HTML JSON XML or redirect to another that does
  # Read / GET
    # User sees
    # show all records inside of the table
    # index actions 
    #   @model_names = Model_name.all

    # single record - id
    #   show action
    #     @model_name = Model_name.find(params[:id])

    # new - show the new record form , create the record in memory
    #   new action
    #     @model_name = Model_name.new

    # edit - show the update form, id
    #   edit action
    #     @model_name = Model_name.find(params[:id])

  # Create / POST
  #   -create a record, must have a new action / form
  #   create action
  #     @model_name = Model_name.new(model_name_params)

  #     if @model_name.save
  #       do 
  #     else
  #       render :new
  #     end

  # Update / PUT PATCH
  #   - edit a record, must have a edit action / form , id
  #     update action
  #     @model_name = Model_name.find(params[:id])
  #     if @model_name.update(model_name_params)
  #       do something
  #     else
  #       render :edit
  #     end

  # Destroy / DELETE 
  #   - delete a record, id
  #   destroy action

  #   Model_name.find(params[:id]).destroy
  #   do something

  # model_name_params
  #   - pass certain attr 

  #   private
  #     def model_name_params
  #       params.require(:model_name).permit(:attr, :everything the table has, :col)
  #     end

  # CALLBACKS 
  #   perform logic at a event / action
  #   before_action
  #   after_action
  #   skip_before_action
  #   skip_after_action
  #                               except:
  # before_action :method_to_call, only: [:index, :show]

  # partials are common views page

  before_action :set_sub, only: [:show, :edit, :update, :destroy] # callback before these methods


  def index
    @subs = Sub.all
  end

  def show
    # @sub = Sub.find(params[:id])
  end

  def new
    @sub = Sub.new
    # relative to the layouts folder
    render partial: 'form'
    # render new.html.erb
  end

  def create
    @sub = Sub.new(sub_params)

      if @sub.save
        redirect_to subs_path
      else
        render :new
      end
  end

  def edit
    # @sub = Sub.find(params[:id])
    render partial: 'form'
    # render edit.html.erb
  end

  def update
    # @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to subs_path
    else
      render :edit
    end
  end

  def destroy
    # Sub.find(params[:id]).destroy
    @sub.destroy
    redirect_to subs_path
  end

  private
    def set_sub # callback here
      @sub = Sub.find(params[:id])
    end
    
    def sub_params
      params.require(:sub).permit(:name)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_sub
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = @sub.topics
  end

  def show
  end

  def new
    @topic = @sub.topics.new
    render partial: 'form'
  end

  def create
    @topic = @sub.topics.new(topic_params)
    
    if @topic.save
      redirect_to [@sub, @topic]
    else
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @topic.update(topic_params)
      redirect_to [@sub, @topic]
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to subs_topics_path
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def set_sub
      @sub = Sub.find(params[:sub_id])
    end

    def topic_params
      params.require(:topic).permit(:name, :body)  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<h1><%= @sub.id ? 'Edit' : 'Create' %></h1>

<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1>Click on a Sub to view content</h1>
<%= link_to 'Create Sub', new_sub_path %>

<ul>
<% @subs.each do |sub| %>
  <li>
    <%= link_to sub.name, sub %>
  </li>
<% end %>
</ul>

app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>

<p> What would you like to do?</p>
<%= link_to 'View Topics', sub_topics_path(@sub) %>
<br/>
<%= link_to 'Edit Sub', edit_sub_path(@sub) %>
<br/>
<%= link_to 'Delete Sub', @sub, method: :delete %>

app/views/topics/_form.html.erb
<%= @topic.id ? 'Edit' : 'Create' %>

<%= form_for [@sub, @topic] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :body %>
  <%= f.text_area :body, required: true%>

  <%= f.submit %>

<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1> All Topics </h1>
<%= link_to 'Create topic', new_sub_topic_path(@sub) %>

<ul>
  <% @topics.each do |topic| %>
    <li>
    <%= link_to topic.name, [@sub, @topic]%>
    </li>
  <% end %>
</ul>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1><%= @sub.name %> <%= @topic.name %> </h1>

<p><%= @topic.body %></p>

<%= link_to 'Edit Topic', edit_sub_topic_path([@sub, @topic]) %>
<%= link_to 'Delete Topic', [@sub, @topic], method: :delete %>
<%= link_to 'Back', sub_topics_path(@sub) %>